Use 3.4-on-4.1 For 3.4 builds
The 4.4 tooling with 3.4 target does not work as intended:

```
environment: line 3: echo: write error: Permission denied
rpmspec: --buildrequires: unknown option
environment: line 3: echo: write error: Permission denied
environment: line 3: echo: write error: Permission denied
error: /etc/rpm/macros.oneshot-generic: line 1: Macro %define is a built-in (%define)
error: /etc/rpm/macros.oneshot-generic: line 2: Macro %define is a built-in (%define)
error: /etc/rpm/macros.perl: line 34: Macro %global is a built-in (%define)
error: /etc/rpm/macros.perl: line 35: Macro %global is a built-in (%define)
rpmbuild: --with: unknown option
```

This means that for using newer Rust versions, we will need to drop 3.4
support.